### ISSUE TITLE
operands could not be broadcast together with shapes (91,811) (91,0) (91,811) 

### ISSUE THREAD

**Issue by zhangsong1213** [ZhengPeng7/SANet-Keras#2]
i try to run generate_datasets, but it came out 'operands could not be broadcast together with shapes (91,811) (91,0) (91,811) '
here is the result

ValueError                                Traceback (most recent call last)
<ipython-input-7-66a905f52af0> in <module>
     26                 k[int(gt[i][1]), int(gt[i][0])] = 1
     27 
---> 28         k = get_density_map_gaussian( k, gt, adaptive_mode=is_adaptive )
     29 
     30         file_path = img_path.replace('.jpg', '.h5').replace('images', 'ground')

~\SANet\utils.py in get_density_map_gaussian(im, points, adaptive_mode, fixed_value, fixed_values)
     65             max(0, p[0]-gaussian_radius):min(density_map.shape[0], p[0]+gaussian_radius+1),
     66             max(0, p[1]-gaussian_radius):min(density_map.shape[1], p[1]+gaussian_radius+1)
---> 67         ] += gaussian_map[y_up:y_down, x_left:x_right]
     68     # density_map[density_map < 0.0003] = 0
     69     density_map = density_map // (np.sum(density_map // num_gt))

ValueError: operands could not be broadcast together with shapes (91,811) (91,0) (91,811)

**Comment by ZhengPeng7** [comment]
Please use the dropbox link to download ShanghaiTech Dataset, since the axes of heads are sometimes negative in that downloaded from Baidu Disk, which is obviously wrong.
The negative axis value made the slice operation looks like [10:-4], and that's the reason why here comes the 0 in (91, 0).
