### ISSUE TITLE
卷积问题

### ISSUE THREAD

**Issue by vvcatstar** [ZhengPeng7/SANet-Keras#3]
您好，我现在在做SAnet的复现，然后发现卷积按照same方式，卷积之后特征图会有白色的边，再反卷积的时候，白边会变得越来越明显，最后学到的就是白边的值。下面是最后encode的特征图和decode最后的特征图。
<img width="200" height="200" src="https://user-images.githubusercontent.com/45086758/62262904-ea202480-b44c-11e9-8558-1cb6b3127aa9.jpg"/> <img width="200" height="200" src="https://user-images.githubusercontent.com/45086758/62262953-189dff80-b44d-11e9-80cc-b792a33b932e.jpg"/>
想请问下，可能是哪里出错了。

**Comment by ZhengPeng7** [comment]
您好, 用same来padding本身应该是没有问题的, 用0填充也不至于带来白色(过大值)特征。你碰到的输出0的问题我当时复现SANet时也是常常出现, 我觉得应该是那几个inception module导致的, 并且如果加上原文中说的解释牵强的IN层, 我是不论怎样都会训成输出0的, 所以我这里并没有加。
我在人群统计训练时, 碰到这种输出0的, 有用过这几种方法解决:
1. 降低学习率(adam),
2. 注意有无漏初始化(std为0.01的标准高斯分布),
3. [SANet]README里写的通过冻结层, 减少梯度回传的距离, 先分别训练获得教合适的权重, 再整体训练,
4. [针对某一数据集训练输出为0]可以在起始一两个epoch中引入别的训练结果正常数据集的数据帮助初期的引导;
希望能对你有帮助.

**Comment by vvcatstar** [comment]
恩，感谢，我试一下分开训练再合起来训练看看效果是不是好一点。之前只用encode训练，是有一定结果的，但是就是收敛以后FP太高了。

**Comment by vvcatstar** [comment]
我分开做了个实验，单独训练decode，dm缩到64x64的，作为decode的输入，使用512x512的dm作为label，最后收敛了，但是基本没有学到东西。之后我有对decode做了类似的inception操作，发现没有特别好的效果，下图分别是输入，预测图，label图。加入decode还没有直接使用encode部分的结果好。学习率前5个epoch为1e-4，之后为1e-5。
<img width="200" height="200" src="https://user-images.githubusercontent.com/45086758/62528172-fa7e3800-b86e-11e9-847f-cd368892941c.jpg"/><img width="200" height="200" src="https://user-images.githubusercontent.com/45086758/62528263-213c6e80-b86f-11e9-98a8-d82055f525bb.jpg"/><img width="200" height="200" src="https://user-images.githubusercontent.com/45086758/62528268-23063200-b86f-11e9-9b10-795956cf1293.jpg"/>

**Comment by ZhengPeng7** [comment]
我觉得你这个第二列图是转置卷积带来的网格效应比较严重, 要说再具体的问题, Decoder为什么像是没训练这样我也不太清楚... 要不你可以读取我的预训练权重作为初始值, 然后跑了试试? 也能确定结构上是否有不一样的地方. 若有发现, 欢迎继续讨论.
