### ISSUE TITLE
SANet on binary images

### ISSUE THREAD

**Issue by AmericaBG** [ZhengPeng7/SANet-Keras#5]
Hi!
First of all, thank you very much for sharing your code! It's a great work.

My question is if the network could be use with binary images as input.

Thanks a lot!
Best regards.

**Comment by ZhengPeng7** [comment]
Of course, I guess fine-tune from the weights saved from training the color images is just okay.
Besides, you can find that there are a lot of images (around 15%) that are actually gray-like images in ShanghaiTech PartA, though they have three channels.
