### ISSUE TITLE
question in "Data generation: run thegenerate_datasets.ipynb“

### ISSUE THREAD

**Issue by stayFoolishWu** [ZhengPeng7/SANet-Keras#6]
ValueError: operands could not be broadcast together with shapes (91,811) (91,0) (91,811)

**Comment by stayFoolishWu** [comment]
ok
i find the answer in closed issue

**Comment by stayFoolishWu** [comment]
dropbox连接失效了~~~

**Comment by ikaroso** [comment]
你好，问下你找到解决的办法了吗，谢谢

**Comment by stayFoolishWu** [comment]
issue里有秒作者用的是dropbox的数据集，但是那个链接失效了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"CodeSniper"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月22日(星期五) 上午9:19
收件人:&nbsp;"ZhengPeng7/SANet-Keras"<SANet-Keras@noreply.github.com&gt;;
抄送:&nbsp;"Wuyi"<774210256@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhengPeng7/SANet-Keras] question in "Data generation: run thegenerate_datasets.ipynb“ (#6)





 
你好，问下你找到解决的办法了吗，谢谢

**Comment by WangXH258** [comment]
> ok
> i find the answer in closed issue

Excuse me, do you find how to solve this problem? I still have the same Error when i run, even i try to download this dataset from google drive but the same error also appear.

**Comment by stayFoolishWu** [comment]
sorry I don't have the answer.&nbsp; I stop running thin code and this paper.&nbsp;


 
---Original---

**Comment by ZhengPeng7** [comment]
Very sorry guys, I didn't receive any notification from Github about this issue...😑

Though this is an old repository, I should be responsible for my codes.

I've uploaded the [Shanghai Tech dataset](https://drive.google.com/file/d/1ZT46P-NRiYAJ7mpG1TzL_ojByGJ33WCd/view?usp=sharing) to my personal google-drive. I hope this can help u solve the problem. I don't know if it's good to share it since I'm not the official author.

BTW, I remember that there is **a totally incorrect GT** in SH-Tech training dataset(not sure whether in A or B), but no one mentioned this before.

I hope these can help you:)

**Comment by stayFoolishWu** [comment]
thank you for your answer.&nbsp; I wish you have more good&nbsp;achievement in AI. thank you again




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhengPeng7/SANet-Keras"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月12日(星期三) 凌晨3:27
收件人:&nbsp;"ZhengPeng7/SANet-Keras"<SANet-Keras@noreply.github.com&gt;;
抄送:&nbsp;"Wuyi"<774210256@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZhengPeng7/SANet-Keras] question in "Data generation: run thegenerate_datasets.ipynb“ (#6)





 
Very sorry guys, I didn't receive any notification from Github about this issue...
 
Though this is an old repository, I should be responsible for my codes.
 
I've uploaded the Shanghai Tech dataset to my personal google-drive. I hope this can help u solve the problem. I don't know if it's good to share it since I'm not the official author.
 
BTW, I remember that there is a totally incorrect GT in SH-Tech training dataset(not sure whether in A or B), but no one mentioned this before.
 
I hope these can help you:)
